# Generated by Django 4.0.3 on 2022-05-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomchat', '0003_alter_roomchat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
