# Generated by Django 4.0.3 on 2022-05-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomchat', '0004_alter_roomchat_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='roomchat.room'),
        ),
    ]
