# Generated by Django 4.0.4 on 2022-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
