# Generated by Django 4.0.3 on 2022-05-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
