# Generated by Django 4.0.3 on 2022-05-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_remove_profile_first_name_remove_profile_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
