# Generated by Django 4.0.4 on 2022-05-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
