# Generated by Django 4.0.4 on 2022-05-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_alter_comment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
